<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" Inherits="AuthorizationManage_OperateScope"
    Title="职务业务操作范围设置" Codebehind="OperateScopeManage.aspx.cs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table>
        <tr>
            <td valign="top">
                <div class="title" style="width: 490px;">
                    请选择职务：
                </div>
                <div class="BorderedArea" style="overflow: auto; width: 500px; height: 400px">
                    <asp:TreeView ID="PositionTreeView" runat="server" AutoGenerateDataBindings="False"
                        ExpandDepth="1" OnSelectedNodeChanged="PositionTreeView_SelectedNodeChanged"
                        ShowLines="True">
                        <HoverNodeStyle BackColor="Gray" />
                        <SelectedNodeStyle BackColor="#000040" ForeColor="White" />
                    </asp:TreeView>
                </div>
            </td>
            <td style="width: 10px;">
                &nbsp;
            </td>
            <td valign="top">
                <asp:Panel ID="OperateUpdatePanel" Visible="false" runat="server">
                    <div class="title" style="width: 340px;">
                        请选择业务操作：
                    </div>
                    <gc:GridView ID="OperateGridView" runat="server" AutoGenerateColumns="False" CssClass="GridView"
                        DataSourceID="OperateDS" DataKeyNames="BusinessOperateId" OnSelectedIndexChanged="OperateGridView_SelectedIndexChanged"
                        AllowPaging="True" AllowSorting="True" OnPageIndexChanging="OperateGridView_PageIndexChanging"
                        OnRowDataBound="OperateGridView_RowDataBound" PageSize="15" OnDataBinding="OperateGridView_DataBinding"
                        OnDataBound="OperateGridView_DataBound">
                        <Columns>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <asp:CheckBox ID="OperateCheckBox" Visible="<%# HasManageRight %>" runat="server" />
                                </ItemTemplate>
                                <HeaderTemplate>
                                    <asp:CheckBox ID="AllOperateCheckBox" Visible="<%# HasManageRight %>" AutoPostBack="true"
                                        runat="server" OnCheckedChanged="AllOperateCheckBox_CheckedChanged" />
                                </HeaderTemplate>
                                <ItemStyle Width="30px" HorizontalAlign="Center" />
                            </asp:TemplateField>
                            <asp:BoundField DataField="BusinessOperateId" HeaderText="BusinessOperateId" ReadOnly="True"
                                SortExpression="BusinessOperateId" Visible="False" />
                            <asp:BoundField DataField="BusinessUseCaseName" HeaderText="业务模块" SortExpression="BusinessUseCaseName">
                                <ItemStyle Width="170px" HorizontalAlign="Center" />
                            </asp:BoundField>
                            <asp:TemplateField HeaderText="业务操作" SortExpression="BusinessOperateName">
                                <ItemTemplate>
                                    <asp:LinkButton CommandName="Select" ID="LinkButton1" Text='<%# Bind("BusinessOperateName") %>'
                                        runat="server"></asp:LinkButton>
                                </ItemTemplate>
                                <ItemStyle Width="157px" HorizontalAlign="Center" />
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <table>
                                <tr class="Header">
                                    <td style="width: 30px;" class="Empty1">
                                        &nbsp;
                                    </td>
                                    <td style="width: 170px;">
                                        业务模块
                                    </td>
                                    <td style="width: 157px;">
                                        业务操作
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="3" class="Empty2 noneLabel">
                                        无
                                    </td>
                                </tr>
                            </table>
                        </EmptyDataTemplate>
                        <HeaderStyle CssClass="Header" />
                        <SelectedRowStyle BackColor="#C0C000" />
                    </gc:GridView>
                </asp:Panel>
            </td>
            <td style="width: 10px;">
                &nbsp;
            </td>
            <td valign="top">
                <asp:Panel ID="UpdatePanel1" runat="server">
                        <div id="ScopeDIV" runat="server" visible="false">
                            <div class="title" style="width: 370px;">
                                请选择业务操作范围（业务数据来源）：
                            </div>
                            <div class="BorderedArea" style="width: 350px; height: 400px; overflow: auto;">
                                <asp:TreeView ID="ScopeTreeView" runat="server" ExpandDepth="2" ShowLines="True">
                                    <HoverNodeStyle BackColor="Gray" />
                                    <SelectedNodeStyle BackColor="#000040" ForeColor="White" />
                                </asp:TreeView>
                            </div>
                            <div style="text-align: center;">
                                <asp:Button ID="SetScopeBtn" Text="设置操作范围" CssClass="button_big" runat="server" OnClick="SetScopeBtn_Click" />
                            </div>
                        </div>
                </asp:Panel>
            </td>
        </tr>
    </table>
    <asp:Panel ID="ScopeListUpdatePanel" Visible="false"
        runat="server">
            <asp:Panel ID="ScopeListPanel" Visible="false" runat="Server">
                <div class="title" style="width: 1260px;">
                    已设置的业务范围：
                </div>
                <gc:GridView ID="ScopeListGridView" runat="server" AutoGenerateColumns="False" DataKeyNames="ScopeOrganziationUnitId"
                    DataSourceID="PositionOperateScopeDS" CssClass="GridView" OnRowDataBound="ScopeListGridView_RowDataBound"
                    OnSelectedIndexChanged="ScopeListGridView_SelectedIndexChanged">
                    <Columns>
                        <asp:TemplateField HeaderText="范围涉及的组织机构" SortExpression="ScopeOrganziationUnitId">
                            <ItemTemplate>
                                <asp:LinkButton ID="ScopedOULinkButton" runat="server" CommandName="select"></asp:LinkButton>
                            </ItemTemplate>
                            <ItemStyle HorizontalAlign="Center" Width="1270px" />
                        </asp:TemplateField>
                    </Columns>
                    <HeaderStyle CssClass="Header" />
                    <EmptyDataTemplate>
                        <table>
                            <tr class="Header">
                                <td class="Empty1" style="width: 1270px;">
                                    范围涉及的组织机构
                                </td>
                            </tr>
                            <tr>
                                <td style="text-align: center;" class="Empty2 noneLabel">
                                    无
                                </td>
                            </tr>
                        </table>
                    </EmptyDataTemplate>
                </gc:GridView>
            </asp:Panel>
    </asp:Panel>
    <asp:ObjectDataSource ID="PositionOperateScopeDS" runat="server" SelectMethod="GetOperateScope"
        TypeName="BusinessObjects.AuthorizationBLL">
        <SelectParameters>
            <asp:Parameter Name="positionId" Type="Int32" />
            <asp:Parameter Name="businessOperateId" Type="Int32" />
        </SelectParameters>
    </asp:ObjectDataSource>
    <asp:SqlDataSource ID="OperateDS" runat="server" ConnectionString="<%$ ConnectionStrings:ERSConnectionString %>"
        SelectCommand="SELECT distinct [BusinessOperateId], [BusinessOperateName], [BusinessOperateDescription], [BusinessUseCaseId], [BusinessUseCaseName], [BusinessUseCaseDescription], [PositionId] FROM [PositionEnabledOperateView] WHERE ([PositionId] = @PositionId) AND ([BusinessUseCaseId] < 100) AND ([BusinessOperateId] > 2000 and [BusinessOperateId] < 4000 ) order by BusinessUseCaseId">
        <SelectParameters>
            <asp:Parameter Name="PositionId" Type="Int32" />
        </SelectParameters>
    </asp:SqlDataSource>
</asp:Content>
