<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" Inherits="AuthorizationManage_PositionRightManage"
    Title="职务权限设置" Codebehind="PositionRightManage.aspx.cs" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table width="1270px" border="0" cellspacing="0" cellpadding="0">
        <tr>
        <td style="width:30px;">&nbsp;</td>
            <td width="654px" valign="top">
                <div class="title2" style="width: 640px;">
                    职位信息</div>
                <div style="width: 654; height: 600px; overflow: auto;">
                    &nbsp;<asp:TreeView ID="OrganizationTreeView" runat="server" ExpandDepth="2" OnSelectedNodeChanged="OrganizationTreeView_SelectedNodeChanged"
                        AutoGenerateDataBindings="False" ShowLines="True">
                        <SelectedNodeStyle BackColor="#000040" ForeColor="White" />
                        <HoverNodeStyle BackColor="Gray" />
                    </asp:TreeView>
                </div>
            </td>
            <td width="504px" valign="top">
                <asp:UpdatePanel ID="RoleUpdatePanel" UpdateMode="Conditional" runat="server">
                    <ContentTemplate>
                        <div class="title3" style="width: 492px;">
                            请选择职务适用的系统角色：
                        </div>
                        <gc:GridView ID="SystemRoleGridView" CssClass="GridView" runat="server" AutoGenerateColumns="False"
                            DataKeyNames="SystemRoleId" DataSourceID="SystemRoleDS">
                            <Columns>
                                <asp:TemplateField>
                                    <ItemTemplate>
                                        <asp:CheckBox ID="SystemRoleCheckBox" runat="server" />
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:BoundField DataField="SystemRoleId" HeaderText="SystemRoleId" InsertVisible="False"
                                    ReadOnly="True" SortExpression="SystemRoleId" Visible="False" ItemStyle-HorizontalAlign="Center" />
                                <asp:BoundField DataField="SystemRoleName" HeaderText="系统角色名称" SortExpression="SystemRoleName"
                                    ItemStyle-Width="200px" ItemStyle-HorizontalAlign="Center" />
                                <asp:BoundField DataField="Description" HeaderText="系统角色说明" SortExpression="Description"
                                    ItemStyle-Width="279px" ItemStyle-HorizontalAlign="Center" />
                            </Columns>
                            <HeaderStyle CssClass="Header" />
                        </gc:GridView>
                        <asp:SqlDataSource ID="SystemRoleDS" runat="server" ConnectionString="<%$ ConnectionStrings:ERSConnectionString %>"
                            SelectCommand="SELECT [SystemRoleId], [SystemRoleName], [Description] FROM [SystemRole]">
                        </asp:SqlDataSource>
                        <div style="text-align: center;">
                            <asp:Button ID="SetPositionRightBtn" Enabled="false" runat="server" CssClass="button_wider"
                                OnClick="SetPositionRightBtn_Click" Text="设置职务系统角色" />
                        </div>
                    </ContentTemplate>
                </asp:UpdatePanel>
            </td>
        </tr>
    </table>
</asp:Content>
